### ISSUE TITLE
Bug in path closing segment?

### ISSUE THREAD

**Issue by nicholaswmin** [duopixel/Method-Draw#17]
Draw a bezier path. On trying to close the path by clicking on the first-placed node the closing segment is drawn in a very strange shape for some reason.

![methoddraw pathbug](https://f.cloud.github.com/assets/3926463/1740700/b7c00604-63d0-11e3-9d49-6287039be519.jpg)

**Comment by duopixel** [comment]
This has been fixed for some time.

**Comment by nicholaswmin** [comment]
Doesn't seem like it,

![screen shot 2015-12-29 at 02 56 06](https://cloud.githubusercontent.com/assets/3926463/12027966/200dbd52-add8-11e5-92fa-5ed1d5e56031.png)


Unfortunately I can't pinpoint the exact steps to reproduce this.
I'm seriously thinking to put some time in tracking this down and fixing it myself after the holidays.

**Comment by duopixel** [comment]
Ah I see, really fixed now, thanks Nicholas.
