### ISSUE TITLE
Line gone when edit vertex in Chrome

### ISSUE THREAD

**Issue by devon** [duopixel/Method-Draw#21]
1). Draw a line with pen, (or any other shape).
2). double click the shape.
3). drag to move the vertex.

The line will gone after several drag move.

The problem only found on chrome (I use Version 35.0.1916.153). It works very well on Safari.

https://www.dropbox.com/s/xiwp0zfdjvydu7w/Screen%20Shot%202014-07-29%20at%2010.40.41%20AM.png

https://www.dropbox.com/s/alxo0fe48a54lyb/line.mp4

**Comment by nicholaswmin** [comment]
+1 found the same fix and added it and now it works like a charm.

**Comment by duopixel** [comment]
commit https://github.com/duopixel/Method-Draw/commit/2c7c5be75397e15afe3f362e3e9d169a88909f37 fixes this.
