### ISSUE TITLE
firefox problem with all tools of editor!!!

### ISSUE THREAD

**Issue by rasoolghafari** [duopixel/Method-Draw#28]
When drawing a rectangle for example, it does not work properly, because i think the editor take the (0,0) coordinate of page instead of canvas

![sc](https://cloud.githubusercontent.com/assets/4728204/7086722/b61da7b4-df73-11e4-81f6-e48a8d09098a.png)

**Comment by duopixel** [comment]
This has been fixed, you can verify at http://editor.method.ac

**Comment by rasoolghafari** [comment]
how can i apply this change to my project?
