### ISSUE TITLE
Chosen Font doesn't show up when image is saved

### ISSUE THREAD

**Issue by catedsel** [duopixel/Method-Draw#31]
I've added fonts to the font library but when I use them and then try to save the image, what's shown on the save screen is a generic font - not the one I chose and that shows up on the canvas when I'm using it.

Here you can see that I've chosen the font - "Cookie" - and it shows up like it should on the canvas -
![screen shot 2015-05-27 at 12 07 29 pm](https://cloud.githubusercontent.com/assets/6278196/7842517/261656fa-0469-11e5-9c8f-3c0e47a9288a.png)

But when I click "File > Save Image" this what shows up on in the new "save" browser window -
![screen shot 2015-05-27 at 12 07 39 pm](https://cloud.githubusercontent.com/assets/6278196/7842531/4348f908-0469-11e5-9981-3c8441afef74.png)

Any help or suggestions would be MUCH appreciated!! Thank you!!

**Comment by catedsel** [comment]
Also, when I inspect the code it shows that the right font - Cookie - is the one selected. It just doesn't visually show up that way.

![screen shot 2015-05-27 at 12 10 15 pm](https://cloud.githubusercontent.com/assets/6278196/7842553/712de054-0469-11e5-8347-a7e025567e4c.png)

**Comment by francescortiz** [comment]
The save command just exports the SVG and loads it in a separate browser window. This new browser window is using your operating system fonts. Embed the SVG into a page that has the Cookie font loaded or install the Cookie font on your system if you want the font to display properly.

**Comment by duopixel** [comment]
@catedsel follow @francescortiz instructions.
