### ISSUE TITLE
Stroke-width not possible on lines with gradients

### ISSUE THREAD

**Issue by EmmaRamirez** [duopixel/Method-Draw#32]
Currently, when you set a linear-gradient as the color, it doesn't allow the user to select stroke-width, instead appearing as "NaN." It can be set manually still.

Here's a screenshot. I'm running current Chrome on Windows 8.
![method-draw-bug](https://cloud.githubusercontent.com/assets/4407518/8393753/1d3ffd60-1cec-11e5-8cb8-16f52abf242b.png)

**Comment by duopixel** [comment]
I can't reproduce on Chrome Mac, can you give me the specific steps for this to happen?

**Comment by duopixel** [comment]
Can't reproduce.
