### ISSUE TITLE
SVG Init with some JSON on it

### ISSUE THREAD

**Issue by alexandrupetrescu94** [duopixel/Method-Draw#35]
I know this is not an issue, but is there a way to init the whole svg with some elements on svgcontent?
I've looked at the code, but I can't find out where the svgcontent instantiates so I can add some JSON on it.
In svgutils.js is the init function which inits the editorContext, where the whole svg appears, but I need one step back, where the svgcontent is added so I could add myself some JSON.

Could you help me please with some informations of where should I add the JSON? 
Thank you in advance.

**Comment by duopixel** [comment]
If I hand an idea of where to get started I'd help you out, but this is SVG-Edit code I haven't touched and it would require me to dive into the same place you are at this moment. Unfortunately I'm short in time, best of luck.
