### ISSUE TITLE
Shape library in not working

### ISSUE THREAD

**Issue by Amarjit1234** [duopixel/Method-Draw#36]
Shape library is not working.Once i have select the one shape, second time I am not able to select the other shape.

**Comment by thomasdunn** [comment]
Same here.  Anyone found a way around this?

**Comment by thomasdunn** [comment]
@Amarjit1234  It looks like there's a 200ms delay to showing the shape library popup on click.  There may be a better way, but I was able to get rid of the delay by changing this line:
https://github.com/duopixel/Method-Draw/blob/ef79f08f68eb57c45f387266dd70566d410d0ef7/editor/src/method-draw.js#L839

to `var time = 0;`

**Comment by Amarjit1234** [comment]
Thanks thomasdunn

**Comment by duopixel** [comment]
This is meant to be able to switch between the toolbar item as a tool and the toolbar item as a menu. It follows the convention of Adobe products (for good or for bad) and svg-edit. The solution @thomasdunn provided is good.
