### ISSUE TITLE
Selecting fonts from an open SVG file...

### ISSUE THREAD

**Issue by cheyennemtnman** [duopixel/Method-Draw#39]
I used File / Open SVG... and when I try to select text object I can  not edit text until I change the font from Null to a font listed... Then I can not see a cursor... Just a green translucent block over the text letters.   Then I am able to change text.  When Selecting a text object you can not edit by clicking the text or double clicking the block... it is treated like a text block object ... when hitting the Text Tool... it creates another text box instead... of editing the text box selected.  Can I alter this in some way?

**Comment by duopixel** [comment]
I can't know what's going on unless you provide a sample file. Unfortunately text editing is very rudimentary and it is unlikely that I can do anything about it :(
