### ISSUE TITLE
Possibly, makefile error

### ISSUE THREAD

**Issue by ambienthack** [duopixel/Method-Draw#43]
Line **rm editor/method-draw.compiled.js** removes compiled js file, so it is not put into **method-draw** directory.

```bash
$(COMPILED_JS):
	java -jar $(CLOSURE) \
		--compilation_level SIMPLE_OPTIMIZATIONS \
		$(CLOSURE_JS_ARGS) \
		--js_output_file $(COMPILED_JS)
	rm editor/method-draw.compiled.js
```

**Comment by duopixel** [comment]
Fixed at https://github.com/duopixel/Method-Draw/commit/8531c6f50f2036f7f82007e06860dd28243a74c7
