### ISSUE TITLE
Not working in Chrome 48 beta

### ISSUE THREAD

**Issue by vadimyer** [duopixel/Method-Draw#44]
Something strange happened today after my browser's update, official demo doesn't work too, I get these types of errors in console:
```
Uncaught TypeError: path.createSVGPathSegLinetoAbs is not a function(anonymous function) @ browser.js:56(anonymous function) @ browser.js:62(anonymous function) @ browser.js:181
svgutils.js:563 Uncaught TypeError: svgedit.browser.supportsSelectors is not a function(anonymous function) @ svgutils.js:563(anonymous function) @ svgutils.js:648
method-draw.js:47 Uncaught TypeError: svgedit.browser.isTouch is not a function(anonymous function) @ method-draw.js:47(anonymous function) @ method-draw.js:4135(anonymous function) @ method-draw.js:4141
contextmenu.js:59 Uncaught ReferenceError: methodDraw is not defined(anonymous function) @ contextmenu.js:59(anonymous function) @ contextmenu.js:68
ext-eyedropper.js:16 Uncaught ReferenceError: methodDraw is not defined(anonymous function) @ ext-eyedropper.js:16
ext-shapes.js:11 Uncaught ReferenceError: methodDraw is not defined(anonymous function) @ ext-shapes.js:11
ext-grid.js:15 Uncaught ReferenceError: methodDraw is not defined(anonymous function) @ ext-grid.js:15
76:57 Uncaught ReferenceError: svgCanvas is not defined
```

**Comment by jarek-foksa** [comment]
This bug can be fixed by including a polyfill for pathSegList API (native support for pathSegList was removed in Chrome 48).

https://github.com/progers/pathseg

**Comment by vadimyer** [comment]
@jarek-foksa thanks for that.

**Comment by duopixel** [comment]
Thanks for the notice @vadimyer and for the solution @jarek-foksa. I'll attempt to incorporate the polyfill later in the day.

I wonder how is that they deprecate without even having the successor API in place, `pathSegList` is indeed cumbersome but it beats manipulating strings.

https://code.google.com/p/chromium/issues/detail?id=539385

**Comment by duopixel** [comment]
Shim included at https://github.com/duopixel/Method-Draw/commit/8531c6f50f2036f7f82007e06860dd28243a74c7
