### ISSUE TITLE
Text misplaced when exporting as PNG

### ISSUE THREAD

**Issue by frequent** [duopixel/Method-Draw#45]
I guess similar to #30 whenever I try to export an SVG to PNG, text elements are badly misplaced. I investigated a little and ended up on [this page](http://apike.ca/prog_svg_text_style.html) which shows the possible attribute values for **text-anchor**. 

Problem:  
**text-anchor** attribute seems to be set to **left** by default, like:
 
      <text stroke-width="3" xml:space="preserve" text-anchor="left" font-family="Arial" font-size="32" id="svg_81" fill="#699dd3">Hello</text>

The value *left* does not exist. To fix and correctly position text I overwrote the svg source and set anchors to *start*. This correctly positioned my text. 

Let me know if I should do a PR for this.

**Comment by duopixel** [comment]
I'll handle this in a week or so, thanks for the notice.

**Comment by duopixel** [comment]
This is fixed, you can verify at http://editor.method.ac
