### ISSUE TITLE
Linear gradients begin/end points not correctly set

### ISSUE THREAD

**Issue by frequent** [duopixel/Method-Draw#46]
Linear gradients are not displayed when exporting to PNG because begin/end point coordinates are not set when creating the gradient. So instead of something like this:

    <linearGradient id="svg_87" x1="0" y1="0" x2="1" y2="0">
       ...
    </linearGradient>

the SVG source will only include this:

    <linearGradient id="svg_87">
       ...
    </linearGradient>

which when rendered as png does not display the gradient at all. The editor color fill menu, linear tab, does include the begin/end point parameters that need to be defined, but they don't make it into the svg source. See below:

![screenshot 2015-12-14 at 4 35 57 pm - edited](https://cloud.githubusercontent.com/assets/729888/11785199/eb5e365c-a280-11e5-9684-0e3d5761af1f.png)

If I set the coordinates by hand in the source code and then export the SVG to PNG, the gradient displays correctly.

**Comment by duopixel** [comment]
Acknowledged. Fix should be easy but I won't have time to fix soon.

**Comment by duopixel** [comment]
This is fixed now.

**Comment by frequent** [comment]
Tops! Thank you very much!
