### ISSUE TITLE
Documentation for integration

### ISSUE THREAD

**Issue by hassenc** [duopixel/Method-Draw#67]
Is there a way to integrate method-draw tools in another app ?
Is it possible to add a documentation to explain which parts to use to integrate it elsewhere ?

Thanks !

**Comment by nicholaswmin** [comment]
@hassenc What kind of integration?

You can just pop it in your app using an `iframe`

**Comment by hassenc** [comment]
Yeah, I was thinking about just reusing the Edition part. But I took a deeper look into the code and It seems tricky because it wasn't developed with that in mind.
